[package]
edition = "2021"
rust-version = "1.60"

name = "da14531-hal"
version = "0.2.2"

[dependencies]
cortex-m = "0.7.5"
da14531 = "0.2"
embedded-hal = {version = "0.2", features = ["unproven"]}
paste = "1.0"

[dependencies.void]
default-features = false
version = "1.0"
