[package]
edition = "2021"
rust-version = "1.60"

name = "da14531-hal"
version = "0.2.0"

[dependencies]
da14531 = "0.2.0"
embedded-hal = {version = "0.2.7", features = ["unproven"]}

[dependencies.void]
default-features = false
version = "1.0.2"
